config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get "/terms", to: "home#terms"
  get "privacy", to: "home#privacy"

  resources :users, only: [ :index, :show ]
  resources :shops  do
    resource :favorites, only: [ :create, :destroy ]
    collection { get :autocomplete }
  end
  get "/favorites", to: "users#favorite"
  get "/mail_test", to: "mail_test#send_mail"
  resource :onboarding, only: [ :update ]

  # ログインしている時のページを新規に開いた先
  authenticated :user do
    root to: "shops#index", as: :authenticated_root
  end
  # ログインしていない時のページを新規に開いた先
  unauthenticated do
    root to: "home#index"
  end

  get "diagnoses/new"
  post "diagnoses/result", to: "diagnoses#result"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def result
    diagnoses = params[:answer].to_s
    if diagnoses == "0"
      render "result_type_a"
    elsif diagnoses == "1"
      render "result_type_b"
    elsif diagnoses == "2"
      render "result_type_c"
    else
      redirect_to diagnoses_new_path, alert: "診断を選択してください"
    end
  end
  # def result
  #   case params[:answer].to_s
  #   when "0"
  #     render "result_type_a"
  #   when "1"
  #     render "result_type_b"
  #   when "2"
  #     render "result_type_c"
  #   else
  #     redirect_to diagnoses_new_path, alert: "診断を選択してください"
  #   end
  # end
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/views/diagnoses/new.html.erb
<% content_for :title, "デート診断" %>

<div class="mt-10 max-w-2xl bg-white p-8 rounded shadow-md mx-4 md:mx-auto">
  <h2 class="text-2xl text-center mb-6 font-bold">次に会うお相手に当てはまるのは？</h2>
  <h2 class=" text-xm text-center mb-6 font-bold text-red-400">1つ選んでください</h2>

  <%= form_with url: diagnoses_result_path, method: :post, local: true, data: { turbo: false } do |f| %>
    <% [
      "優しい目元で、共感力が高く人の気持ちに寄り添える。",
      "清潔感のある服装で、気配り上手な性格。",
      "ファッションに気を配りつつ、言葉に敏感で思いやりがある。"
    ].each_with_index do |desc, i| %>
      <div class="flex items-start space-x-4 mb-4 ">
        <%= f.radio_button :answer, i, id: "answer_#{i}", class: "radio radio-lg radio-accent mt-1" %>
        <%= f.label :answer, desc, for: "answer_#{i}", class: "text-lg leading-relaxed" %>
      </div>
    <% end %>

    <div class="mt-6 text-center">
      <%= f.submit "診断結果へ", class: "btn bg-[#D5A273] text-white hover:bg-[#b77f53] px-6 text-lg" %>
    </div>
  <% end %>
</div>

app/views/diagnoses/result_type_a.html.erb
<div class="max-w-2xl mx-auto text-center mt-10 bg-white rounded-xl shadow-lg p-8">
  <h1 class="text-3xl font-bold mb-8">ぴったりなお店が見つかりました！</h1>

  <p class="text-sm text-gray-500 mb-6">おしゃれな彼女には雰囲気が決めてかも？</p>

  <div class="mb-10">
    <p class="text-xl font-semibold mb-2">おすすめカテゴリー</p>
    <p class="text-lg">「イタリアン」</p>

    <%= link_to "おすすめカテゴリーをmapで見る", shops_path(q: { category_name_eq: "イタリアン" }), class: "inline-block mt-4 px-6 py-3 bg-[#D5A273] text-white font-semibold rounded hover:bg-[#b77f53]" %>
  </div>

  <div class="mb-10">
    <p class="text-xl font-semibold mb-2">おすすめのお店</p>
    <p class="text-lg">「ZenZero 名駅店」</p>
    <p class="text-lg">個室も有！予約はお早めに！</p>

    <% if shop = Shop.find_by(title: "ZenZero 名駅店") %>
      <%= link_to "お店詳細", shop_path(shop), class: "inline-block mt-4 px-6 py-3 bg-[#D5A273] text-white font-semibold rounded hover:bg-[#b77f53]" %>
    <% end %>
  </div>
</div>

app/views/diagnoses/result_type_b.html.erb
<div class="max-w-xl mx-auto text-center mt-10 bg-white rounded-xl shadow-lg p-8">
  <h1 class="text-3xl font-bold mb-8">ぴったりなお店が見つかりました！</h1>

  <p class="text-sm text-gray-500 mb-6">社交的な彼女、だけど自然な距離感を保つのがコツ？
</p>

  <div class="mb-10">
    <p class="text-xl font-semibold mb-2">おすすめカテゴリー</p>
    <p class="text-lg">「フレンチ」</p>

    <%= link_to "おすすめカテゴリーをmapで見る", shops_path(q: { category_name_eq: "フレンチ" }), class: "inline-block mt-4 px-6 py-3 bg-[#D5A273] text-white font-semibold rounded hover:bg-[#b77f53]" %>
  </div>

  <div class="mb-10">
    <p class="text-xl font-semibold mb-2">おすすめのお店</p>
    <p class="text-lg">「Casual Dining Iris（アイリス）」</p>
    <p class="text-lg">落ち着いた店内でゆったり会話ができる！</p>

    <% if shop = Shop.find_by(title: "Casual Dining Iris（アイリス）") %>
      <%= link_to "お店詳細", shop_path(shop), class: "inline-block mt-4 px-6 py-3 bg-[#D5A273] text-white font-semibold rounded hover:bg-[#b77f53]" %>
    <% end %>
  </div>
</div>

app/views/diagnoses/result_type_c.html.erb
<div class="max-w-xl mx-auto text-center mt-10 bg-white rounded-xl shadow-lg p-8">  <h1 class="text-3xl font-bold mb-8">ぴったりなお店が見つかりました！</h1>

  <p class="text-sm text-gray-500 mb-6">信頼され、頼られる存在になれるかがポイント？</p>

  <div class="mb-10">
    <p class="text-xl font-semibold mb-2">おすすめカテゴリー</p>
    <p class="text-lg">「ビストロ」</p>

    <%= link_to "おすすめカテゴリーをmapで見る", shops_path(q: { category_name_eq: "ビストロ" }), class: "inline-block mt-4 px-6 py-3 bg-[#D5A273] text-white font-semibold rounded hover:bg-[#b77f53]" %>
  </div>

  <div class="mb-10">
    <p class="text-xl font-semibold mb-2">おすすめのお店</p>
    <p class="text-lg">「BISTRO N°1 -名駅店-」</p>
    <p class="text-lg">いつもとは違う雰囲気で乾杯</p>

  <% if shop = Shop.find_by(title: "BISTRO N°1 -名駅店-") %>
    <%= link_to "お店詳細", shop_path(shop), class: "inline-block mt-4 px-6 py-3 bg-[#D5A273] text-white font-semibold rounded hover:bg-[#b77f53]" %>
  <% end %>
  </div>
</div>