config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get "/terms", to: "home#terms"
  get "privacy", to: "home#privacy"

  resources :users, only: [ :index, :show ]
  resources :shops  do
    resource :favorites, only: [ :create, :destroy ]
    collection { get :autocomplete }
  end
  get "/favorites", to: "users#favorite"
  get "/mail_test", to: "mail_test#send_mail"
  resource :onboarding, only: [ :update ]

  # ログインしている時のページを新規に開いた先
  authenticated :user do
    root to: "shops#index", as: :authenticated_root
  end
  # ログインしていない時のページを新規に開いた先
  unauthenticated do
    root to: "home#index"
  end

  get "diagnoses/new"
  post "diagnoses/result", to: "diagnoses#result"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :shops

  def self.ransackable_attributes(auth_object = nil)
    %w[name created_at updated_at]
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/models/scene.rb
class Scene < ApplicationRecord
  has_many :shop_scenes, dependent: :destroy
  has_many :shops, through: :shop_scenes
  validates :name, presence: true, uniqueness: true

  def self.ransackable_attributes(_auth = nil)
  %w[id name slug created_at updated_at]
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user, optional: true
  has_many :users, through: :favorites
  belongs_to :category, optional: true

  has_many :favorites, dependent: :destroy

  scope :favorited_by, ->(user_id) {
    joins(:favorites).where(favorites: { user_id: user_id }).distinct
  }

  has_many :shop_scenes, dependent: :destroy
  has_many :scenes, through: :shop_scenes
  has_many_attached :images

  validates :title, presence: true
  validates :address, presence: true
  validates :category_id, presence: true
  validate :scenes_count_within_limit

  # jsにカテゴリー名を呼ぶためのこのメソッドが呼び出される
  def category_name
    category.present? ? category.name : "カテゴリ未設定"
  end

  def scenes_name
    scenes.first ? scenes.first.name : "シーン未設定"
    scenes.first&.name || "シーン未設定"
  end

  def self.ransackable_attributes(auth_object = nil)
  [ "title", "address", "body", "category_id", "created_at", "latitude", "longitude" ]
  end

  def self.ransackable_associations(auth_object = nil)
  %w[scenes shop_scenes category]
  end

  private
  def scenes_count_within_limit
    ids = Array(scene_ids).reject(&:blank?)
    if ids.size > 2
      errors.add(:scenes, "は2つまで選択できます")
    end
  end
end

app/models/shop_scene.rb
class ShopScene < ApplicationRecord
  belongs_to :shop
  belongs_to :scene
end

app/models/user.rb
class User < ApplicationRecord
  after_create :send_welcome_email

  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable,
          :omniauthable, omniauth_providers: [ :google_oauth2 ]

  has_many :shops, dependent: :nullify
  has_many :favorites, dependent: :destroy
  has_many :favorite_shops, through: :favorites, source: :shop

  validates :name, presence: true, on: :create

  # お気に入り追加 削除 重複確認
  def favorite(shop)
    favorites.find_or_create_by!(shop_id: shop.id)
  end

  def unfavorite(shop)
    favorites.where(shop_id: shop.id).destroy_all
  end

  def favorite?(shop)
    favorites.exists?(shop_id: shop.id)
  end

  private

  def send_welcome_email
    UserMailer.welcome_email(self).deliver_later
  end
end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def result
    diagnoses = params[:answer].to_s
    if diagnoses == "0"
      render "result_type_a"
    elsif diagnoses == "1"
      render "result_type_b"
    elsif diagnoses == "2"
      render "result_type_c"
    else
      redirect_to diagnoses_new_path, alert: "診断を選択してください"
    end
  end
  # def result
  #   case params[:answer].to_s
  #   when "0"
  #     render "result_type_a"
  #   when "1"
  #     render "result_type_b"
  #   when "2"
  #     render "result_type_c"
  #   else
  #     redirect_to diagnoses_new_path, alert: "診断を選択してください"
  #   end
  # end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shop, only: [ :create, :destroy ]

  def favorite
    @favorite_shops = current_user.favorite_shops
  end

  def create
    current_user.favorite(@shop)
  end

  def destroy
    current_user.unfavorite(@shop)
  end

  private

  def set_shop
    @shop = Shop.find(params[:shop_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
  def terms; end
  def privacy; end
end

app/controllers/mail_test_controller.rb
class MailTestController < ApplicationController
  def send_mail
    Rails.logger.info("[MAIL_DEBUG] #{ActionMailer::Base.smtp_settings.inspect}")

    mail = ActionMailer::Base.mail(
      from: ENV.fetch("MAIL_FROM", "noreply@dokodate.jp"),
      to:   "あなたのメールアドレス",
      subject: "Mailtrapテスト",
      body: "Hello from dokodate!"
    )
    mail.deliver_now
    render plain: "OK"
  rescue => e
    render plain: "NG: #{e.class} #{e.message}", status: 500
  end
end

app/controllers/onboarding_controller.rb
class OnboardingController < ApplicationController
  before_action :authenticate_user!

  def update
    #受け取ったパラメータがtrueならっていう処理 trueに変更、違うなら何もしない
    if params[:hide_onboarding_banner] == true || params[:hide_onboarding_banner] == "true"
      current_user.update(hide_onboarding_banner: true)
    end
    head :no_content
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]

  def index
    @q = Shop.ransack(params[:q])
    scope = @q.result.includes(:category, :scenes).order(created_at: :desc)

    # #ログイン中のユーザーがお気に入り登録したShopだけ取得
    if params[:favorited].present? && current_user
      scope = scope.favorited_by(current_user.id)
    end

    @shops = scope

    respond_to do |format|
    format.html
    format.json { render json: @shops.to_json(
      only: [ :id, :title, :address, :latitude, :longitude ],
      methods: [ :category_name, :scenes_name ]
      )
    }
    end
  end

  def autocomplete
    q = params[:q].to_s
    @shops = Shop.where("title ILIKE :q OR address ILIKE :q", q: "#{q}%").limit(5)
    render partial: "shops/autocomplete"
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = current_user.shops.new(shop_params)
    if @shop.save
      redirect_to shops_path, notice: "お店を登録しました", status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @shop = current_user.shops.find(params[:id])
  end

  def update
    @shop = current_user.shops.find(params[:id])

    if @shop.update(shop_params)
      redirect_to shop_path(@shop), notice: "お店を更新しました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

 def destroy
    @shop = current_user.shops.find(params[:id])
    @shop.destroy
      redirect_to shops_path, status: :see_other, notice: "お店を削除しました"
  end

  private
  def shop_params
    params.require(:shop).permit(:title, :address, :latitude, :longitude, :category_id, :page, images: [], scene_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def favorites
    @q = current_user.favorite_shops.ransack(params[:q])
    @favorite_shops = @q.result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = "")
    base_title = "DokoDate"
    title.present? ? "#{title} | #{base_title}" : base_title
  end
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/onboarding_helper.rb
module OnboardingHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
  <div class="px-4">
    <% flash.each do |type, msg| %>
      <% next if msg.blank? %>
      <% klass =
        case type.to_sym
        when :notice, :success then "bg-green-100 text-green-800"
        when :alert,  :error   then "bg-red-100 text-red-800"
        else "bg-slate-100 text-slate-800"
        end %>
      <p class="<%= klass %> p-2 my-2 rounded shadow-sm"><%= msg %></p>
    <% end %>
  </div>

app/views/layouts/_footer.html.erb
    <footer class="bg-yellow-400 text-base text-gray-800 text-right px-2 py-6">
      <div class="flex justify-between items-center">
        <div class="ml-4">© 2025 MyApp</div>
        <div class="mr-4">
          <a href=/terms class="hover:underline">利用規約</a> /
          <a href=/privacy class="hover:underline">プライバシーポリシー</a>
        </div>
      </div>
    </footer>

app/views/layouts/_header.html.erb
<header class="bg-white  py-6 px-6 flex justify-between items-center border-b-5 border-dashed border-amber-500">
  <!-- 左：ロゴ -->
  <% if user_signed_in? %>
  <div>
    <%= link_to shops_path, data: { turbo: false }, class: "hover:text-primary" do %>
        <%= image_tag "logo.png", alt: "ロゴ画像", width: 150 %>
      <% end %>
    <% else %>
      <%= link_to root_path, data: { turbo: false }, class: "hover:text-primary" do %>
        <%= image_tag "logo.png", alt: "ロゴ画像", width: 150 %>
      <% end %>
    <% end %>
  </div>

  <!-- モバイル用ハンバーガーアイコン -->
  <button
    id="menu-toggle"
    class="md:hidden text-amber-400 hover:text-amber-500"
    onclick="document.getElementById('mobile-menu').classList.toggle('hidden')"
  >
    <!-- 三本線 -->
    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="M4 6h16M4 12h16M4 18h16"/>
    </svg>
  </button>

  <!-- PC用メニュー -->
  <nav class="hidden md:flex space-x-10 items-center">
    <% if user_signed_in? %>
      <%= link_to "お店一覧 >", shops_path, class: "text-xl py-4 px-6 rounded-xl bg-amber-500 text-white font-bold hover:bg-amber-600", data: { turbo: false } %>
      <%= link_to "お気に入り >", shops_path(favorited: 1) , class: "text-xl text-amber-400 hover:text-amber-500", data: { turbo: false } %>
      <%= link_to "お店投稿 >", new_shop_path	, class: "text-xl text-amber-400 hover:text-amber-500" %>
      <%= link_to "デート診断 >", diagnoses_new_path	, class: "text-xl text-amber-400 hover:text-amber-500" %>
      <%= link_to "ログアウト >", destroy_user_session_path, class: "text-xl text-amber-400 hover:text-amber-500",  data: { turbo_method: :delete}  %>
    <% else %>
      <%= link_to "デート診断 >", diagnoses_new_path	, class: "text-xl text-amber-400 hover:text-amber-500 " %>
      <%= link_to "ログイン >", new_user_session_path, class: "text-xl text-amber-400 hover:text-amber-500" %>
      <%= link_to "会員登録", new_user_registration_path, class: "text-xl py-4 px-6 rounded-xl bg-amber-500 text-white font-bold hover:bg-amber-600" %>
    <% end %>
  </nav>
</header>

<!-- スマホ用メニュー（初期は非表示） -->
<nav id="mobile-menu" class="hidden bg-white px-6 py-4 space-y-3">
  <ul class="flex flex-col gap-2 p-2">
    <!-- 共通 -->
    <li><%= link_to "デート診断 >", diagnoses_new_path, class: "text-amber-500 hover:text-amber-600 font-bold" %></li>

    <% if user_signed_in? %>
      <li><%= link_to "お店一覧 >", shops_path, class: "text-amber-500 hover:text-amber-600 font-bold", data: { turbo: false } %></li>
      <li><%= link_to "お気に入り >", favorites_path, class: "text-amber-500 hover:text-amber-600 font-bold", data: { turbo: false } %></li>
      <li><%= link_to "お店投稿 >", new_shop_path, class: "text-amber-500 hover:text-amber-600 font-bold" %></li>
      <li>
        <%= link_to "ログアウト >", destroy_user_session_path,
              data: { turbo_method: :delete, turbo_confirm: "ログアウトしますか？" },
              class: "text-amber-500 hover:text-amber-600 font-bold" %>
      </li>
    <% else %>
      <li><%= link_to "ログイン >", new_user_session_path, class: "text-amber-500 hover:text-amber-600 font-bold" %></li>
      <li><%= link_to "会員登録 >", new_user_registration_path, class: "text-amber-500 hover:text-amber-600 font-bold" %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", type: "module", "data-turbo-track": "reload", defer: true %>
    <link href="https://fonts.googleapis.com/css2?family=Mochiy+Pop+One&display=swap" rel="stylesheet">
    <script
    src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.dig(:google, :GOOGLE_MAPS_API_KEY) %>&libraries=marker,places&loading=async">
    </script>

    <meta name="description" content="地図から直感的にお店を探せるアプリです。">
    <!-- OGP -->
    <meta property="og:title" content="デート迷子にさよなら！ | ドコデート" />
    <meta property="og:description" content="地図から直感的にお店を探せるアプリです。" />
    <meta property="og:image" content="<%= asset_url('ogp.png') %>" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:type" content="website" />
    <!-- Twitterカードも追加 -->
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="csrf-token" content="<%= form_authenticity_token %>">
  </head>

<body class="flex flex-col min-h-screen bg-yellow-100">
  <!-- 1) ヘッダー -->
  <%= render "layouts/header" %>

  <%= render "layouts/flash" %>

  <!-- 3) コンテンツ ローディングアニメーションをメインの中で表示-->
  <main class="relative flex-1">
    <div id="loading" class="absolute inset-0 flex items-center justify-center bg-white/80 hidden">
      <div class="loader"></div>
    </div>
    <%= yield %>
  </main>

  <%= render "layouts/footer" %>
</body>

</html>